default: &default
  adapter: postgresql
  encoding: unicode
  host: postgresdb
  username: postgres
  password: password
  pool: 5

development:
  <<: *default
  database: atena_development


test:
  <<: *default
  database: atena_test

production:
  <<: *default
  database: atena_production
  username: atena
  password: <%= ENV["atena_DATABASE_PASSWORD"] %>